# Generated by Django 4.0.4 on 2022-05-02 21:09

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=30)),
                ('unique_id', models.SlugField(blank=True, default=None, max_length=255)),
                ('profile_pic', models.ImageField(default='uploads/profile_pics/default.jpg', upload_to='uploads/profile_pics')),
                ('birthdate', models.DateField()),
                ('last_edit', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('background', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/characters')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='uploads/entities')),
                ('hp', models.PositiveIntegerField()),
                ('atk', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('trigger', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='uploads/events')),
                ('chronology', models.IntegerField()),
                ('trigger', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('editedAt', models.DateTimeField(auto_now=True)),
                ('maxParticipants', models.PositiveIntegerField()),
                ('isPublic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tickbox',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('editAt', models.DateTimeField(auto_now=True)),
                ('checked', models.BooleanField(default=False)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='uploads/stories')),
                ('optimalPlayers', models.PositiveIntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('editedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('trigger', models.CharField(max_length=10, unique=True)),
                ('entities', models.ManyToManyField(to='blablapp.entity')),
                ('events', models.ManyToManyField(to='blablapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('hit', models.IntegerField(default=0)),
                ('joinedAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('leftAt', models.DateTimeField(null=True)),
                ('kicked', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('characterId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blablapp.character')),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blablapp.room')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='storyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blablapp.story'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageContent', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='uploads/messages')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('editedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('quoted', models.BooleanField(default=False)),
                ('whispered', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blablapp.room')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('sentAt', models.DateTimeField(auto_now_add=True)),
                ('approvedAt', models.DateTimeField(null=True)),
                ('refusedAt', models.DateTimeField(null=True)),
                ('recieverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContactReceiver', to=settings.AUTH_USER_MODEL)),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContactSender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('hp', models.PositiveIntegerField()),
                ('atk', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('actions', models.ManyToManyField(to='blablapp.action')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='characterClassId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blablapp.characterclass'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='characters',
            field=models.ManyToManyField(blank=True, to='blablapp.character'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Whisper',
            fields=[
                ('messageId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blablapp.message')),
                ('receiverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WhisperReceiver', to=settings.AUTH_USER_MODEL)),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WhisperSender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('messageId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='QuoteSender', serialize=False, to='blablapp.message')),
                ('quotedId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='QuoteReceiver', to='blablapp.message')),
            ],
        ),
        migrations.CreateModel(
            name='EntityInstance',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blablapp.entity')),
                ('currentHP', models.PositiveIntegerField(null=True)),
                ('currentATK', models.PositiveIntegerField(null=True)),
                ('currentDEF', models.PositiveIntegerField(null=True)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blablapp.room')),
            ],
            bases=('blablapp.entity',),
        ),
    ]
