# Generated by Django 4.0.4 on 2022-05-02 12:17

import blablapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('hp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('defense', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='uploads/entities')),
                ('hp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('trigger', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='uploads/events')),
                ('chronology', models.IntegerField()),
                ('trigger', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageContent', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='uploads/messages')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('editedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True)),
                ('quoted', models.BooleanField(default=False)),
                ('whispered', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('editedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True)),
                ('maxParticipants', models.IntegerField(blank=True)),
                ('isPublic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('defaultId', models.IntegerField(default=blablapp.models.User.id_by_default, unique=True)),
                ('birthdate', models.DateField(blank=True)),
                ('nickname', models.EmailField(max_length=100)),
                ('profilePic', models.ImageField(default='uploads/profile_pics/default.jpg', upload_to='uploads/profile_pics')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('editedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityInstance',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blablapp.entity')),
                ('currentHP', models.IntegerField(blank=True)),
                ('currentATK', models.IntegerField(blank=True)),
                ('currentDEF', models.IntegerField(blank=True)),
            ],
            bases=('blablapp.entity',),
        ),
        migrations.CreateModel(
            name='Whisper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blablapp.message')),
                ('receiverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WhisperReceiver', to='blablapp.user')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WhisperSender', to='blablapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tickbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('editAt', models.DateTimeField(auto_now=True)),
                ('checked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blablapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='uploads/stories')),
                ('optimalPlayers', models.IntegerField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('editedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True)),
                ('deleted', models.BooleanField(default=False)),
                ('trigger', models.CharField(max_length=10, unique=True)),
                ('triggerCount', models.IntegerField(blank=True)),
                ('entities', models.ManyToManyField(to='blablapp.entity')),
                ('events', models.ManyToManyField(to='blablapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False)),
                ('nickname', models.TextField(blank=True, max_length=30)),
                ('hit', models.IntegerField(default=0)),
                ('joinedAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('leftAt', models.DateTimeField(blank=True)),
                ('kicked', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blablapp.room')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blablapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='storyId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blablapp.story'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='QuoteSender', to='blablapp.message')),
                ('quotedId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='QuoteReceiver', to='blablapp.message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blablapp.room'),
        ),
        migrations.AddField(
            model_name='message',
            name='senderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blablapp.user'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('sentAt', models.DateTimeField(auto_now_add=True)),
                ('approvedAt', models.DateTimeField(blank=True)),
                ('refusedAt', models.DateTimeField(blank=True)),
                ('recieverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContactReceiver', to='blablapp.user')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContactSender', to='blablapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('background', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/characters')),
                ('characterClassId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blablapp.characterclass')),
            ],
        ),
    ]
