# Generated by Django 4.0.4 on 2022-05-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['title'], 'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['user', 'characterClass'], 'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='characterclass',
            options={'ordering': ['name'], 'verbose_name': 'Character Class', 'verbose_name_plural': 'Character Classes'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['sender', 'approved'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='entityinstance',
            options={'verbose_name': 'Entity Instance', 'verbose_name_plural': 'Entity Instances'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['title'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-isPublic', 'createdAt'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['title'], 'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterModelOptions(
            name='tickbox',
            options={'ordering': ['createdAt'], 'verbose_name': 'Tickbox', 'verbose_name_plural': 'Tickboxes'},
        ),
    ]
