# Generated by Django 4.0.4 on 2022-05-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityinstance',
            name='entityId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blablapp.entity'),
        ),
    ]
