# Generated by Django 4.0.4 on 2022-05-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomparticipant',
            name='character',
            field=models.ForeignKey(help_text='Choose your player', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='blablapp.character', verbose_name='Character'),
        ),
    ]
