# Generated by Django 4.0.4 on 2022-05-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='characterclass',
            options={'verbose_name': 'Character Class', 'verbose_name_plural': 'Character Classes'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='tickbox',
            options={'verbose_name': 'Tickbox', 'verbose_name_plural': 'Tickboxes'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='chronology',
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True, help_text='Not Required'),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.TextField(blank=True, help_text='Not Required'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a character image', upload_to='characters'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='atk',
            field=models.PositiveIntegerField(help_text='Maximum 20'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='defense',
            field=models.PositiveIntegerField(help_text='Maximum 20'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='description',
            field=models.TextField(blank=True, help_text='Not Required'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='hp',
            field=models.PositiveIntegerField(help_text='Maximum 20'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='atk',
            field=models.PositiveIntegerField(help_text='Maximum 20'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='defense',
            field=models.PositiveIntegerField(help_text='Maximum 20'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='hp',
            field=models.PositiveIntegerField(help_text='Maximum 20'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a Creature / NPC picture', upload_to='entities'),
        ),
        migrations.AlterField(
            model_name='entityinstance',
            name='currentATK',
            field=models.PositiveIntegerField(help_text='Not Required', null=True),
        ),
        migrations.AlterField(
            model_name='entityinstance',
            name='currentDEF',
            field=models.PositiveIntegerField(help_text='Not Required', null=True),
        ),
        migrations.AlterField(
            model_name='entityinstance',
            name='currentHP',
            field=models.PositiveIntegerField(help_text='Not Required', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Not Required'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a picture for your Event', upload_to='events'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, help_text='Add an image to your message', upload_to='messages'),
        ),
        migrations.AlterField(
            model_name='message',
            name='messageContent',
            field=models.TextField(verbose_name='Message Content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='quoted',
            field=models.BooleanField(default=False, help_text='Is the message a quote?'),
        ),
        migrations.AlterField(
            model_name='message',
            name='whispered',
            field=models.BooleanField(default=False, help_text='Is the message a whisper?'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.jpg', help_text='Upload a profile picture', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='unique_id',
            field=models.SlugField(editable=False, max_length=255, null=True, unique=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='isPublic',
            field=models.BooleanField(default=False, help_text='Change room visibility', verbose_name='Room visibility'),
        ),
        migrations.AlterField(
            model_name='room',
            name='maxParticipants',
            field=models.PositiveIntegerField(verbose_name='Maximum Participants'),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='characterId',
            field=models.ForeignKey(help_text='Choose your player', on_delete=django.db.models.deletion.RESTRICT, to='blablapp.character', verbose_name='Character'),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='hit',
            field=models.IntegerField(default=0, help_text='Hit points taken by the participant', verbose_name='Hit Point'),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='isAdmin',
            field=models.BooleanField(default=False, help_text='Determine if the participant is the DM', verbose_name='Is DM'),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='nickname',
            field=models.CharField(help_text='By default the user nickname', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True, help_text='Not Required'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a picture for your Story', upload_to='stories'),
        ),
        migrations.AlterField(
            model_name='story',
            name='optimalPlayers',
            field=models.PositiveIntegerField(help_text='Optimal number of players for this story.', verbose_name='Optimal Number of Players'),
        ),
    ]
