# Generated by Django 4.0.4 on 2022-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
