# Generated by Django 4.0.4 on 2022-05-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='story_description',
            field=models.TextField(blank=True, help_text='Not Required'),
        ),
        migrations.AddField(
            model_name='room',
            name='story_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
