# Generated by Django 4.0.4 on 2022-05-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0002_rename_recieverid_contact_receiverid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isTriggered',
            field=models.BooleanField(default=False),
        ),
    ]
