# Generated by Django 4.0.4 on 2022-05-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0002_room_story_description_room_story_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='story_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='story_name',
        ),
    ]
