# Generated by Django 4.0.4 on 2022-05-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0002_entityinstance_entityid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityinstance',
            name='entityId',
        ),
    ]
