# Generated by Django 4.0.4 on 2022-05-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0002_alter_action_options_alter_character_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='actions',
            field=models.ManyToManyField(related_name='classes', to='blablapp.action'),
        ),
        migrations.AlterField(
            model_name='story',
            name='entities',
            field=models.ManyToManyField(related_name='stories', to='blablapp.entity'),
        ),
        migrations.AlterField(
            model_name='story',
            name='events',
            field=models.ManyToManyField(related_name='stories', to='blablapp.event'),
        ),
    ]
