# Generated by Django 4.0.4 on 2022-05-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0002_remove_entity_trigger'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entityinstance',
            unique_together={('room', 'trigger')},
        ),
    ]
