# Generated by Django 4.0.4 on 2022-05-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0002_alter_action_options_alter_character_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterField(
            model_name='entityinstance',
            name='roomId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blablapp.room'),
        ),
    ]
