# Generated by Django 4.0.4 on 2022-05-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0003_alter_entityinstance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='approvedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='refusedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
