# Generated by Django 4.0.4 on 2022-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0003_alter_event_options_alter_story_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['roomId', 'createdAt'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['createdAt', 'isPublic'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomparticipant',
            options={'verbose_name': 'Room Participant', 'verbose_name_plural': 'Room Participants'},
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(help_text='Upload a character image', upload_to='characters'),
        ),
    ]
