# Generated by Django 4.0.4 on 2022-05-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0003_alter_myuser_birthdate_alter_myuser_characters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='unique_id',
            field=models.SlugField(blank=True, default=None, unique=True),
        ),
    ]
