# Generated by Django 4.0.4 on 2022-05-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0004_alter_contact_approvedat_alter_contact_refusedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chronology',
            field=models.IntegerField(help_text='Event order in a Story', null=True),
        ),
    ]
