# Generated by Django 4.0.4 on 2022-05-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0004_alter_myuser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='unique_id',
            field=models.SlugField(blank=True, default=None),
        ),
    ]
