# Generated by Django 4.0.4 on 2022-05-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0005_alter_myuser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
    ]
