# Generated by Django 4.0.4 on 2022-05-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0006_alter_roomparticipant_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='chronology',
        ),
    ]
