# Generated by Django 4.0.4 on 2022-05-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0006_alter_myuser_birthdate_alter_myuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
