# Generated by Django 4.0.4 on 2022-05-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0007_alter_room_deletedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='deletedAt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='maxParticipants',
            field=models.IntegerField(),
        ),
    ]
