# Generated by Django 4.0.4 on 2022-05-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0008_alter_room_deletedat_alter_room_maxparticipants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='unique_id',
            field=models.SlugField(blank=True, default=None, max_length=255),
        ),
    ]
