# Generated by Django 4.0.4 on 2022-05-02 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0009_alter_myuser_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='deletedAt',
        ),
        migrations.AlterField(
            model_name='character',
            name='characterClassId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blablapp.characterclass'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='storyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blablapp.story'),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='characterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blablapp.character'),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='leftAt',
            field=models.DateTimeField(null=True),
        ),
    ]
