# Generated by Django 4.0.4 on 2022-05-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0010_remove_room_deletedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='optimalPlayers',
            field=models.IntegerField(),
        ),
    ]
