# Generated by Django 4.0.4 on 2022-05-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0011_alter_story_deletedat_alter_story_optimalplayers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='triggerCount',
        ),
    ]
