# Generated by Django 4.0.4 on 2022-05-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0012_remove_story_triggercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomparticipant',
            name='nickname',
            field=models.TextField(max_length=30),
        ),
    ]
