# Generated by Django 4.0.4 on 2022-05-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0014_alter_roomparticipant_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
