# Generated by Django 4.0.4 on 2022-05-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0016_alter_characterclass_atk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='atk',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='defense',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='hp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='approvedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='refusedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
