# Generated by Django 4.0.4 on 2022-05-02 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0017_alter_action_title_alter_characterclass_atk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickbox',
            name='id',
        ),
        migrations.AlterField(
            model_name='tickbox',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
