# Generated by Django 4.0.4 on 2022-05-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0018_remove_tickbox_id_alter_tickbox_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='atk',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='entity',
            name='defense',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='entity',
            name='hp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
