# Generated by Django 4.0.4 on 2022-05-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablapp', '0019_alter_entity_atk_alter_entity_defense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityinstance',
            name='currentATK',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entityinstance',
            name='currentDEF',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entityinstance',
            name='currentHP',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
