# Generated by Django 4.1.2 on 2022-12-16 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0003_remove_myuser_last_connexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='deletedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleter', to=settings.AUTH_USER_MODEL),
        ),
    ]
